name: pub_package_dependency_csv
version: 0.1.0
environment:
  sdk: ">=1.24.3 <2.0.0"
dependencies:
  args: ^1.5.0
  csv: ^3.3.0
  collection: ^1.14.6
  path: ^1.5.1
  pub_semver: ^1.4.2
  yaml: ^2.1.13
